### ISSUE TITLE
You are doing it too fast. Lower the rate or contact isox AT vulners DOT

### ISSUE THREAD

**Issue by defec8edc0de** [vulnersCom/nmap-vulners#10]
Does your NSE script require tender-scanning?

I get the following output:

`22/tcp    open  ssh         syn-ack ttl 64 OpenSSH 4.7p1 Debian 8ubuntu1 (protocol 2.0)
| vulners: 
|_  cpe:/a:openbsd:openssh:4.7p1: You are doing it too fast. Lower the rate or contact isox AT vulners DOT com.`

...when scanning a metasploitable instance with following nmap command:

`nmap -sS -Pn -n -vvv --reason -A --version-all -p- -T3 --script vulners -oA metasploitable-vulnerstest-A-allports 192.168.126.132`

If your NSE script requires making Web-API requests during scanning, this is an absolute no-go! On many engagements, you won't have an Internet connection...and n̶o̶t̶ ̶e̶v̶e̶n̶ ̶m̶e̶n̶t̶i̶o̶n̶i̶n̶g̶ ̶t̶h̶e̶ ̶p̶r̶i̶v̶a̶c̶y̶ ̶c̶o̶n̶c̶e̶r̶n̶s̶.̶.̶.̶ this contributes to serious privacy and non-disclosure-agreement violations.

**Comment by vulnersCom** [comment]
Hi!

> If your NSE script requires making Web-API requests during scanning, this is an absolute no-go! On many engagements, you won't have an Internet connection...and n̶o̶t̶ ̶e̶v̶e̶n̶ ̶m̶e̶n̶t̶i̶o̶n̶i̶n̶g̶ ̶t̶h̶e̶ ̶p̶r̶i̶v̶a̶c̶y̶ ̶c̶o̶n̶c̶e̶r̶n̶s̶.̶.̶.̶ this contributes to serious privacy and non-disclosure-agreement violations.

Yep, it's doing web-api requests. It is online tool for now. But don't worry, we can't see the host you are scanning and even your IP address if you are using proxy. 
Because there is no way to hold Vulners database and whole backend logics on the local machine.
We are working under the idea of making offline database like in our 'getsploit' tool.
