### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by advaithm** [vulnersCom/nmap-vulners#16]
when I run the follwing nmap -sV --script vulners this is the output
>nmap -sV --script vulners 192.168.1.1
Starting Nmap 7.70 ( https://nmap.org ) at 2019-01-28 11:32 India Standard Time
Nmap scan report for 192.168.1.1
Host is up (0.0010s latency).
All 1000 scanned ports on 192.168.1.1 are filtered
MAC Address: C8:D7:79:A4:69:2F (Qingdao Haier TelecomLtd)

Service detection performed. Please report any incorrect results at https://nmap
.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 64.43 seconds
vulners yields no output pls fix

**Comment by vulnersCom** [comment]
All 1000 scanned ports on 192.168.1.1 are filtered

Looks like there is no open ports ;)
And nmap did not detected any software.

**Comment by GMedian** [comment]
Hello.

I once again can not think of a possible reason for that. 
- Could you please make sue that the problem persists across different hosts rather than a single one?
- Is this the very exact command you are running (no additional flags or anything):
```
nmap -sV --script vulners 192.168.1.1
```
- Try running with verbose output just to verify the script is actually working.
- Check your network connection. After all the script makes use of a remote DB. It should not be an issue but still.

If everything is OK and you still get a full result without script and none with it please take note of the previous issue - https://github.com/vulnersCom/nmap-vulners/issues/11 - it seems much like yours and has some suggestions.

As for your last comment:
```
if there are no vulnerabilities add a feature that informs the user of that
```
We have decided not to do that because of the *nmap way*: just say nothing if you do not find anything.

**Comment by advaithm** [comment]
yes the problem does persist please fix it 
i am running windows 8.1

**Comment by GMedian** [comment]
Hello.

Unfortunately it still seems like the problem is on your end. 
Please check your environment. I have just verified the script is working on my windows installation.

**Comment by advaithm** [comment]
okay thanks it might be that it is pirated?

**Comment by eigauravkumar** [comment]
**Actual Output:** 
$ nmap --script nmap-vulners -sV 10.100.100.166

Starting Nmap 7.70 ( https://nmap.org ) at 2020-02-20 16:45 IST
Nmap scan report for 10.100.100.166
Host is up (0.00075s latency).
Not shown: 999 closed ports
PORT   STATE SERVICE VERSION
53/tcp open  domain  dnsmasq 2.79

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 10.74 seconds

**Expected Output**
| vulners: 
|   cpe:/a:thekelleys:dnsmasq:2.79: 
|_    	CVE-2019-14834	4.3	https://vulners.com/cve/CVE-2019-14834

Please help me why I am not getting the vulnerabilities ?

**Comment by advaithm** [comment]
What?

**Comment by eigauravkumar** [comment]
Thank You @advaithm,
But How can I get the expected Output having vulners in the output?

**Comment by advaithm** [comment]
Open a new issue to report incorrect detection
